language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: wwQtDhT8q0iQC43m6hxPvFKn5r8DbGGdpO6+B0razUTgqaxBdew2P0guEhQe+lXcddCUAYOezv8rofwXlsGeXQOkozL3YeLu2zufVqHPY6PrKJAtOEzTy96KTejgbImlqFriwX50TDz4LF8urk8qnyWkd/JI6S26ISPMuusbP4hmzyX4rgQYKaLQPpvs/+31T7kloOtQdU4f6VPBrNAldREh3cNsLH79Dh8thyxUdanwRMqfwAdmLGjIMWhxACg8kdH2Lg9XBOG8Zxr04AjqunOxYAVuJaSekAsZA5pwtlM8hhJmfLV/qsYiEbJKXyQ8tVZkMq89kTbhX1bwZE+Rv5p5WJ/BW/uiwgzfpOLEIKckXJN5jYg4c8XqhWEOFp2av51uYhuGEQZRcQKZmIDhBMIEpYH3WGkQ4ByWC4FYRjYYftggMqN6dhUHBTUDeKeLcO8rXtZ6VmB980SG6Y0f+beiFHTgT3CtzbkWezcpxo0HO70YysVM1weHMY9C67LMA4j2QmbZV7LxaqZ9qRIZdggwAFYeoaMSz8qfuUe/YqAZVscWz2yQOe/jfkABawxFXg3hEsn1e8xFR0tP2Hw2lAdFlLFRb8rPs4ibXBzbGx9b9S09qH8by4jUzrAr54DwFdDe0vz0QHLxlUmUbWlxWeAGCgrV0/PF3vlZpyp/JhI=
  app: cs-addressbook
  on:
    repo: ashrafcourses/addressbook
