language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: gnjgsjnv8IbtkrZCnavusJJ7JYLez4e1G7PtGKSVitaA+yS1SrG+SLoFU9UnyIvsoFdwI4j9Dec4C0aikiPadoiv9ZsP085Yz5DlO5OheaicB+fuzmGFkZETUym6Iv+d/TsSNoWE6el00GIDAyT0GA+MqgSPY52RxujyO2LnwB63bjwanHOddncfV6vR67e5SbMot1+fDFdoUSFXI+4cWRCxz0Plqlmwy+3STjMIc7G9crglF0W+CzZuz4urAJvNG+3qwbpQybbPj3yRq/wB6NPY8H8ZoMjQvN6u0y/NnjqDhYelDrqdoZcIJbs9uqGRVrYXel35uL59iVv0z+cc937cPKmQK6WaeSryptbOBwuOIc4NXujlpzYXPfVab4LawAbdHgKpXutx3mDSHo43y35AZEU90zvjzKeU7T2ILaFKLcUeRKPCsSB4rs5ODFT2+gTf5Yqv0DPtusoeZKQtDb/1Yz2aSwbcS66kSc3wCXMsvwu/t0CpPJPBxKe7ZN9ALI7V4kj/9zF+Js6+kzA0yWyOz3SEjrpLqeT2kijmnWoiXKop8xJbbFsZBnUmHhlN2JrWV+kDzVjmIlsqSu5Gb9CMIpIZ+zb9D2M/qvX3TQbiszrHePzn1oPG4BuPbfAYzd2ft39aprhoAtxhMHz2GwYthcZy6jOr6yRmw6YYjQI=
    app: cs-addressbook
